{% set version = "1.2" %}

package:
  name: prosstt
  version: {{ version }}

source:
  fn: prosstt-{{ version }}.tar.gz
  url: https://github.com/soedinglab/prosstt/archive/v{{ version }}.tar.gz
  sha256: f3c1227e0e01147d65f4cb6a12c35a6e99873d0908762a49c16886100e7e1c90

build:
  number: 0
  script: pip install .
  skip: True  # [not py36]

requirements:
  build:
    - python
    - pip
  run:
    - python
    - numpy
    - scipy
    - pandas
    - matplotlib
    - jupyter
    - newick
    - scanpy

test:
  imports:
    - prosstt
    - prosstt.tree
    - prosstt.simulation
    - prosstt.count_model
    - prosstt.tree_utils
    - prosstt.sim_utils

about:
  home: https://github.com/soedinglab/prosstt/
  license: GPL3
  license_file: LICENSE
  summary: "PROSSTT: PRObabilistic Simulations of ScRNA-seq Tree-like Topologies"